# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  lint:
    working_directory: ~/aframe-atom-particles
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-deps-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-deps-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package.json" }}
      # lint
      - run:
         name: lint
         command: npm run lint

workflows:
  version: 2
  verify:
    jobs:
      - lint
